source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RACPhotos_Example' do
  pod "RACPhotos", :path => "../"

  target 'RACPhotos_Tests' do
    pod 'Quick', '~> 0.9'
    pod 'Nimble', '~> 4.0'
  end
end
