source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RACPhotos_Example', :exclusive => true do
  pod "RACPhotos", :path => "../"
end

target 'RACPhotos_Tests', :exclusive => true do
  pod "RACPhotos", :path => "../"

  pod 'Quick', '~> 0.8'
  pod 'Nimble'
end
